### ISSUE TITLE
GitHub Actions

### ISSUE THREAD

**Issue by jbosse** [localstack/docs#103]
This action does not work. It fails with `pip: not found`. 
So I added 
```
        run: |
          apt-get update -y
          apt-get install -y docker python3-pip python-dev build-essential
          # install LocalStack cli and awslocal
         ...
```
Then it failed with `docker: not found`

**Comment by jbosse** [comment]
I was able to get my action working by adding localstack as a service. I hijacked the health check to initialize my default bucket "uploads"

```

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      aws_local:
        image: localstack/localstack
        ports:
          - "4566:4566"
        env:
          SERVICES: "sqs,s3"
          DEFAULT_REGION: us-east-1
          FORCE_NONINTERACTIVE: 1
          AWS_ACCESS_KEY_ID: MYACCESSKEY
          AWS_SECRET_ACCESS_KEY: wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww=
        options: >-
          --health-cmd "awslocal s3 mb s3://uploads"
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5
```
