### ISSUE TITLE
Elastic Compute Cloud (EC2) - using locally tagged image in the pipeline

### ISSUE THREAD

**Issue by Akm0d** [localstack/docs#151]
I am able to have my tests pass locally by tagging a local ubuntu:focal image as specified in the documentation:
  
`docker tag ubuntu:focal localstack-ec2/ubuntu-focal-ami:ami-000001`

When using localstack in the pipeline, however, I am not sure how to tag an image I am using in the same way, I tried aliasing the image, but that doesn't seem to work.  Am I missing something?

```
tests-pro:
  stage: tests-localstack-pro
  services:
    - name: localstack/localstack
      alias: localstack
    - name: ubuntu:focal
      alias: localstack-ec2/ubuntu-focal-ami:ami-000001
```

**Comment by Akm0d** [comment]
The project I'm doing this in is open source, if my specific use-case adds any insight: https://gitlab.com/vmware/idem/idem-aws/-/merge_requests/276

**Comment by Akm0d** [comment]
I figured it out, the trick is to use docker:dind

```
tests-pro:
  stage: tests-localstack-pro
  services:
    - name: localstack/localstack
      alias: localstack
    - name: docker:dind
  script:
    - docker run ubuntu:focal
    - docker tag ubuntu:focal localstack-ec2/ubuntu-focal-ami:ami-000001
```
