### ISSUE TITLE
Connect ElastiCache from SpringBoot Application run on another Machine

### ISSUE THREAD

**Issue by meiyouya** [localstack/docs#1591]
I created a Replication groups in cluster mode but I got a error when I connect it with SpringBoot.
error msg:
```text
 i.l.core.cluster.RedisClusterClient      : Connection refused: /127.0.0.1:4513
 i.l.core.cluster.RedisClusterClient      : Connection refused: /127.0.0.1:4519
 i.l.core.cluster.RedisClusterClient      : Connection refused: /127.0.0.1:4520
 i.l.core.cluster.RedisClusterClient      : Connection refused: /127.0.0.1:4512
 i.l.core.cluster.RedisClusterClient      : Connection refused: /127.0.0.1:4514
 i.l.core.cluster.RedisClusterClient      : Connection refused: /127.0.0.1:4515
```

my yml:

```yaml
spring:
  cloud:
    aws:
      credentials:
        access-key: xxxx
        secret-key: xxxx
      region:
        static: ap-northeast-1
      endpoint: http://localhost.localstack.cloud:4566
  data:
    redis:
      cluster:
        nodes: localhost.localstack.cloud:4512,localhost.localstack.cloud:4513,localhost.localstack.cloud:4514,localhost.localstack.cloud:4515,localhost.localstack.cloud:4519,localhost.localstack.cloud:4520
```
